# Generated by Django 3.2 on 2022-01-06 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5, verbose_name='Ticker')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('data_hora_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor investido')),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço médio')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(verbose_name='Data de movimentação')),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1, verbose_name='Tipo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Valor total')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacao_acao', to='acoes.acao', verbose_name='Ação')),
            ],
        ),
    ]
