# Generated by Django 3.2 on 2022-01-06 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carteira',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carteira_acao', to='acoes.acao'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteira_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
