# Generated by Django 3.2 on 2022-01-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.AlterModelOptions(
            name='carteira',
            options={'verbose_name': 'Carteira', 'verbose_name_plural': 'Carteiras'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterField(
            model_name='carteira',
            name='acao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carteira_acao', to='acoes.acao'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Valor total'),
        ),
    ]
