# Generated by Django 3.2 on 2022-01-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0003_auto_20220106_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carteira',
            options={'ordering': ['acao__ticker'], 'verbose_name': 'Carteira', 'verbose_name_plural': 'Carteiras'},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Preço Venda'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='acao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carteira_acao', to='acoes.acao', verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
