# Generated by Django 3.2 on 2022-01-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0004_auto_20220111_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='preco_venda',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='preco_medio_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Preço Médio Venda'),
        ),
    ]
