# Generated by Django 3.2 on 2022-01-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0006_alter_acao_data_hora_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='ticker',
            field=models.CharField(max_length=5, unique=True, verbose_name='Ticker'),
        ),
    ]
