# Generated by Django 3.2 on 2022-01-17 13:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acoes', '0007_alter_acao_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carteira_acao', to='acoes.acao', verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='preco_medio',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço médio'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='valor_investido',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor investido'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='preco_medio_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Médio Venda'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor total'),
        ),
        migrations.AlterUniqueTogether(
            name='carteira',
            unique_together={('user', 'acao')},
        ),
    ]
